### ISSUE TITLE
Confusing error if toolchain get before system get

### ISSUE THREAD

**Issue by ghitchens** [ghitchens/bake#18]
This is on a machine which already had built blinky, already had the current toolchains and systems, but didn't have any Bakefile.lock entry for rpi2 yet.

Also note it's not clear if t needed to download the toolchain or not (it didn't), but seem to imply that it did.

``` sh
gmb:blinky garth$ bake toolchain get
=> Get toolchain for target rpi2
** (MatchError) no match of right hand side value: [recipe: {"nerves/rpi2", "~> 0.1"}]
    (bake) lib/bake/cli/toolchain.ex:58: anonymous fn/4 in Bake.Cli.Toolchain.get/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2

gmb:blinky garth$ bake system get
=> Checking system for target rpi2
=> System nerves/rpi2 at 0.1.0 up to date
gmb:blinky garth$ bake toolchain get
=> Get toolchain for target rpi2
=> Toolchain nerves/arm-unknown-linux-gnueabihf Downloaded
=> Unpacking toolchain nerves/arm-unknown-linux-gnueabihf
gmb:blinky garth$ ls
Bakefile    Bakefile.lock   README.md   config      lib     mix.exs     mix.lock    rel     test
gmb:blinky garth$ bake toolchain get
=> Get toolchain for target rpi2
=> Toolchain nerves/arm-unknown-linux-gnueabihf Downloaded
=> Unpacking toolchain nerves/arm-unknown-linux-gnueabihf
gmb:blinky garth$
```

**Comment by mobileoverlord** [comment]
fixed in master
