### ISSUE TITLE
`bake help` crashes

### ISSUE THREAD

**Issue by ghitchens** [ghitchens/bake#21]
```gmb:nerves-examples garth$ bake help
*\* (FunctionClauseError) no function clause matching in String.capitalize/1
    (elixir) lib/string.ex:569: String.capitalize(nil)
    (bake) lib/bake/cli/help.ex:19: Bake.Cli.Help.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2

gmb:nerves-examples garth$```

**Comment by mobileoverlord** [comment]
fixed in master
